<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PhotoPick.Core\PhotoPick.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="app_icon.ico" />
    <Resource Include="app_icon.png" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>MaviSelect</AssemblyName>
    <RootNamespace>PhotoPick.Desktop</RootNamespace>
    <ApplicationIcon>app_icon.ico</ApplicationIcon>
    <Product>MaviSelect</Product>
    <Title>MaviSelect</Title>
    <Version>1.0.0</Version>
    <Company>Mavi Studio</Company>
    <Description>MaviSelect — Culling Ultrarrápido de Fotos para Adobe Lightroom Classic</Description>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>


  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>
</Project>
